VenvProjectBlog/VenvProjectBlog/urls.py
from django.conf.urls import url
from django.contrib import admin

from django.conf.urls import include
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
    url(r'', include('mainpage.urls')),
]

VenvProjectBlog/blog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
	url(r'^blog$', views.list, name='list'),
	url(r'^blog/post/(?P<pk>[0-9]+)$', views.detail, name='detail'),
	url(r'^blog/archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
	url(r'^blog/category/(?P<pk>[0-9]+)/$', views.category, name='category'),
	url(r'^blog/search$', views.search, name='search'),
]

VenvProjectBlog/comments/urls.py
from django.conf.urls import url
from . import views

app_name = 'comments'
urlpatterns = [
	# url(r'^comment/post/(?P<pk>[0-9]+)/$', views.post_comment, name='post_comment'),
	url(r'^comment/post/(?P<pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

VenvProjectBlog/mainpage/urls.py
from django.conf.urls import url
from . import views

app_name="mainpage"
urlpatterns=[
	url(r"^[index]?$", views.pagetxt, name='pagetxt'),
	url(r'^about', views.pageabout, name='pageabout'),
]

VenvProjectBlog/blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.utils.six import python_2_unicode_compatible

from django.urls import reverse
@python_2_unicode_compatible
class Category(models.Model):
	'''文章类别类'''
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name

@python_2_unicode_compatible
class Tag(models.Model):
	'''文章标签类'''
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name

@python_2_unicode_compatible
class Posts(models.Model):
	'''文章内容类'''
	title = models.CharField(max_length=70)
	body = models.TextField()
	created_time = models.DateTimeField()
	#创建时间
	modified_time = models.DateTimeField()
	#修改时间
	excerpt = models.CharField(max_length=200, blank=True)
	#摘要
	category = models.ForeignKey(Category)
	tags = models.ManyToManyField(Tag, blank=True)
	author = models.ForeignKey(User)
	showNum = models.BigIntegerField(default=0)
	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:detail',kwargs={'pk':self.pk})

	class Meta:
		ordering = ['-created_time', 'title']

VenvProjectBlog/comments/models.py
#-*- coding:utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from django.utils.six import python_2_unicode_compatible

@python_2_unicode_compatible
class Comment(models.Model):
	"""docstring for Comment"""
	name = models.CharField(max_length=100)
	email = models.EmailField(max_length=255)
	text = models.TextField()
	created_time = models.DateTimeField(auto_now_add=True)

	post = models.ForeignKey('blog.Posts')
	
	def __str__(self):
		return self.text[:20]

VenvProjectBlog/mainpage/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from django.utils.six import python_2_unicode_compatible
from django.contrib.auth.models import User
@python_2_unicode_compatible
class mainpage(models.Model):
	title = models.CharField(max_length=100)
	body = models.TextField()
	create_time = models.DateTimeField()
	author = models.ForeignKey(User) 
	def __str__(self):
		return self.title
	class Meta:
		ordering = ['-create_time',]

class about(models.Model):
	pictitle = models.CharField(max_length=50)
	pictxt = models.TextField()
	about = models.TextField()

VenvProjectBlog/comments/forms.py
#-*- coding:utf-8 -*-
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['name', 'email', 'text']

		widgets = {
		'name':forms.TextInput(attrs={'placeholder':'名字',}),
		'email':forms.TextInput(attrs={'placeholder':'邮箱',}),
		}

VenvProjectBlog/blog/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from .models import Posts, Category
from django.shortcuts import get_object_or_404
from comments.forms import CommentForm
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

import markdown


def  list(request):
	# return HttpResponse('欢迎访问我的主页')
	post_list = Posts.objects.all()
	#分页
	ps = Paginator(post_list, 8)
	pn = request.GET.get('page')
	try:
		post_list = ps.page(pn)
	except PageNotAnInteger:
		post_list = ps.page(1)
	except EmptyPage:
		post_list = ps.page(ps.num_pages())

	return render(request, 'blog/list.html',context={
			'post_list':post_list
		})

def detail(request, pk):
	post = get_object_or_404(Posts, pk=pk)
	md = markdown.Markdown(extensions=[
		'markdown.extensions.extra', 
		'markdown.extensions.codehilite', 
		#'markdown.extensions.toc',
		#锚点美化
		TocExtension(slugify=slugify),
		])
	post.showNum +=1
	post.save()
	post.body = md.convert(post.body)

	form = CommentForm()
	comment_list = post.comment_set.all()
	context = {
	'post':post,
	'form':form,
	'comment_list':comment_list,
	'Toc':md.toc,
	}

	return render(request, 'blog/detail.html', context=context)

def archives(request, year, month):
	post_list = Posts.objects.filter(created_time__year=year, created_time__month=month)
	return render(request, 'blog/list.html', context={'post_list':post_list})

def category(request, pk):
	cate = get_object_or_404(Category, pk=pk)
	post_list = Posts.objects.filter(category=cate)
	return render(request, 'blog/list.html', context={'post_list':post_list})

def search(request):
	q = request.GET.get('q')
	error_msg = ''
	if not q:
		error_msg = "输入搜索数据为空"
		return render(request, 'blog/list.html', context={'error_msg':error_msg})

	post_list = Posts.objects.filter(title__icontains=q)
	if len(post_list) == 0:
		context = {
		'error_msg':"查询失败，该条件下没有查询结果",
		'text_css':"danger",
		'post_list':post_list,
		}
	else:
		context = {
		'error_msg':"查询成功，该条件下查询结果如下",
		'text_css':"success",
		'post_list':post_list,
		}
	return render(request, 'blog/list.html', context=context)

VenvProjectBlog/comments/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import get_object_or_404,redirect
from blog.models import Posts

from .models import Comment
from .forms import CommentForm

def post_comment(request,pk):
	post = get_object_or_404(Posts, pk=pk)
	if request.method == "POST":
		form = CommentForm(request.POST)

		if form.is_valid():
			comment = form.save(commit=False)
			comment.post = post
			comment.save()
			return redirect(post)

		else:
			comment_list = post.comment_set.all()
			context = {
			'post':post,
			'form':form,
			'comment_list':comment_list,
			}
			return render(request, 'blog/detail.html',context=context)

	return redirect(post)

VenvProjectBlog/mainpage/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render

# Create your views here.
from django.shortcuts import get_object_or_404
from .models import mainpage,about
import markdown

def pagetxt(request):
	main = get_object_or_404(mainpage,pk=1)
	main.body = markdown.markdown(main.body, extensions=[
		'markdown.extensions.extra',
		'markdown.extensions.codehilite',
		'markdown.extensions.toc'])
	return render(request, 'blog/main.html', context={'main':main})

def pageabout(request):
	main =get_object_or_404(about)
	main.pictxt = markdown.markdown(main.pictxt, extensions=[
		'markdown.extensions.extra',
		'markdown.extensions.codehilite',
		'markdown.extensions.toc'])
	main.about = markdown.markdown(main.about, extensions=[
		'markdown.extensions.extra',
		'markdown.extensions.codehilite',
		'markdown.extensions.toc'])
	return render(request, 'blog/about.html', context={'main':main})

VenvProjectBlog/templates/base.html
{% extends 'basemain.html' %}
{% load blog_tags %}
{% block basemain %}
<div class="row">
	<div class="col-md-7 col-sm-8 col-xs-12">
		{% block main %}
		{% endblock main %}
	</div>
	<div class="col-md-3 col-sm-4 col-xs-12">
		<div class="panel panel-primary">
			<div class="panel-heading">最新文章</div>
	  		<ul class="list-group">
	  			{% get_recent_posts as recent_post_list %}
				{% for post in recent_post_list %}
	  			<li class="list-group-item">
	  				<a href="{{ post.get_absolute_url }}">
	  				<span class="fa fa-chevron-circle-right fa-lg">&nbsp;{{ post.title }}&nbsp;</span>
	    			</a>
	    		</li>
	    		{% endfor %}
	 		</ul>
		</div>
		<div class="panel panel-primary">
			<div class="panel-heading">时间归档</div>
		 	<ul class="list-group">
		 	{% archives as date_list %}
			{% for date in date_list %}
	  			<li class="list-group-item">
	    			<a href="{% url 'blog:archives' date.year date.month %}">
						<span class="fa fa-clock-o fa-lg">&nbsp;{{ date.year }}年{{ date.month }}月&nbsp;</span>
					</a>
	    		</li>
	    	{% endfor %}
	  		</ul>
		</div>
		<div class="panel panel-primary">
			<div class="panel-heading">文章分类</div>
			<ul class="list-group">
			{% get_categories as categors %}
			{% for ca in categors %}
	    		<li class="list-group-item">
	    			<a href="{% url 'blog:category' ca.pk %}">
						<span class="fa fa-tag fa-lg">&nbsp;{{ ca.name }}&nbsp;({{ca.num_post}})</span>
					</a>
	    		</li>
	    	{% endfor %}
	  		</ul>
		</div>
	</div>
	<div class="col-md-2 col-sm-0 col-xs-0">
	</div>
</div>
{% endblock basemain %}

VenvProjectBlog/templates/basemain.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
	<head>
		<title>Hank’s_Blog</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	    <link rel="shortcut icon" href="/Img/faviconCQ.ico" type="image/x-icon">
	    <!-- css -->
	    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
		<link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	    <link href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet">
	    <!-- js -->
	    <script src="https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
	    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
	    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
		<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	</head>
	<body>
		<header id="site-header">
			<nav class="navbar navbar-default navbar-static-top" role="navigation">
				<div class="container-fluid">
						<div class="row">
							<div class="col-md-12 col-sm-12 col-xs-12">
								<div class="col-md-2 col-sm-0 col-xs-0">
								</div>
								<div class="col-md-2 col-sm-4 col-xs-0 hidden-xs">
			  						<p class="navbar-text" style="text-align: center">
			  							<a href="{% url 'mainpage:pageabout' %}" class="navbar-link" style="color:blue">Hank</a> 
			  							's Blog&nbsp;&nbsp;&nbsp;&nbsp;
										<a href="#" title="站内搜索,未完成" data-toggle="modal" data-target="#myModal">
											<i class="fa fa-search fa-lg"></i>
										</a>
									</p>
								</div>
								<div class="col-md-8 col-sm-8 col-xs-12">
			  						<ul class="nav nav-pills">
			  							<li role="presentation"><a href="{% url 'mainpage:pagetxt' %}" title="主页"><i class="fa fa-home fa-lg"></i>主页</a></li>
			  							<li role="presentation"><a href="{% url 'blog:list' %}" title="博客"><span><i class="fa fa-book fa-lg"></i>博客</span></a></li>
			  							<li role="presentation"><a href="{% url 'mainpage:pageabout' %}" title="关于作者"><i class="fa fa-user-circle-o fa-lg"></i>关于</a></li>
									</ul>
								</div>
							</div>
						</div>
				</div>
			</nav>
		</header>
		<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  		<div class="modal-dialog" role="document">
	    		<div class="modal-content">
	      			<div class="modal-header">
	       				 <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	       				 	<span aria-hidden="true">&times;</span>
	       				 </button>
	        			<h4 class="modal-title" id="myModalLabel">站内检索</h4>
	      			</div>
	      			<div class="modal-body">
	        			<form role="search" method="get" action="{% url 'blog:search' %}">
	        				<div class="input-group">
	          				<input type="text" class="form-control" name="q" placeholder="请输入关键字">
	          				<span class="input-group-btn">
	        					<button class="btn btn-default" type="submit">Go!</button>
	      					</span>
	      					</div>
	       				</form>
	      			</div>
	      			<div class="modal-footer">
	      				<p><i class="fa fa-warning fa-lg">该搜索功能有待完善</i><p>
	      			</div>
	    		</div>
	  		</div>
		</div>
		<div class="content-body">
			<div class="container-fluid">
			{% block basemain %}
			{% endblock basemain %}
			</div>
		</div>
		<footer id="site-footer">
			<hr />
			<div class="container">
				<div class="row">
					<div class="col-md-4 col-sm-2 col-xs-0"></div>
					<div class="col-md-4 col-sm-8 col-xs-12">
						<p style="text-align: center"> 人生苦短，我用Python---- <a href="/admin" title="后台" target="_blank"><span class=" fa fa-user-circle fa-lg"></span>后台管理</a></p>
					</div>
					<div class="col-md-4 col-sm-2 col-xs-0"></div>
				</div>
			</div>
		</footer>
	</body>
</html>

VenvProjectBlog/templates/blog/about.html
{% extends 'basemain.html' %}
{% block basemain %}
<div class="row">
	<div class="col-md-4 col-sm-3 col-xs-1"></div>
	<div class="col-md-4 col-sm-6 col-xs-10">
		    <div class="thumbnail">
		      <img src="/Img/me.jpg">
		      <div class="caption">
		        <h3>{{main.pictitle}}</h3>
		        <p>{{main.pictxt|safe}}</p>
		      </div>
			</div>
	</div>
	<div class="col-md-4 col-sm-3 col-xs-1"></div>
</div>
<hr />
<div class="row">
	<div class="col-md-3 col-sm-2 col-xs-0"></div>
	<div class="col-md-6 col-sm-8 col-xs-12">
		{{main.about|safe}}
	</div>
	<div class="col-md-3 col-sm-2 col-xs-0"></div>
</div>
{% endblock basemain %}

VenvProjectBlog/templates/blog/detail.html
{% extends 'basemain.html' %}
{% block basemain %}

<div class="container-fluid">
	<div class="row">
		<div class="col-md-2 col-sm-1 col-xs-0">
		</div>
		<div class="col-md-8 col-sm-10 col-xs-12">
			<div class="page-header">
  				<h2>{{ post.title }} <small></small></h2>
			</div>
			<p>
				<span class="fa fa-user fa-fw"></span>{{post.author}}&nbsp;&nbsp;&nbsp;<span class="fa fa-clock-o fa-fw"></span>{{post.created_time}}&nbsp;&nbsp;&nbsp;<span class="fa fa-tags fa-fw"></span>{{ post.category.name }}
			</p>
			<div class="panel">
				<div class="panel-heading">
					{{ Toc|safe }}
				</div>
	  			<div class="panel-body">
	  				{{ post.body|safe }}
	  			</div>
	  			<div class="panel-footer">
	  				<p>
		  				<strong>最近修改:{{ post.modified_time }}</strong>&nbsp;&nbsp;&nbsp;有帮助:
		  				<a href="#" title="有帮助"><span class="fa fa-thumbs-o-up">(-)</span></a><br />
		  				分享到:<a href="#" title="微博"><span class="fa fa-weibo text-danger">微博</span></a>&nbsp;&nbsp;<a href="#" title="微信"><span class="fa fa-weixin text-success">微信</span></a>
	  				</p>
	  			</div>
			</div>
			<hr />
		</div>
		<div class="col-md-2 col-sm-1 col-xs-0">
		</div>
	</div>
	<!--评论区行-->
	<div class="row">
		<div class="col-md-3 col-sm-1 col-xs-0">
		</div>
		<div class="col-md-6 col-sm-7 col-xs-10">
			<div class="panel panel-primary">
				<div class="panel-heading"><h3>留下你的小想法( • ̀ω•́ )✧</h3></div>
				<form class="form-horizontal" action="{% url 'comments:post_comment' post.pk %}" method="post">
				<div class="panel-body">
						{% csrf_token %}
						<div class="form-group">
							<label class="col-sm-2 control-label" for="{{ form.name.id_for_label }}">名字</label>
							<div class="col-sm-10">
					      		<input class="form-control" id="id_name" maxlength="100" name="name" placeholder="名字" type="text" required="">
					      		{{ form.name.errors }}
					      	</div>
					    </div>
					    <div class="form-group">
					      	<label class="col-sm-2 control-label" for="{{ form.email.id_for_label }}">邮箱</label>
					      	<div class="col-sm-10">
						      	<input class="form-control" id="id_email" maxlength="255" name="email" placeholder="邮箱" type="text" required="">
						      	{{ form.name.errors }}
					      	</div>
					    </div>
					    <div class="form-group">
					      	<label class="col-sm-2 control-label" for="{{ form.text.id_for_label }}">评论</label>
					      	<div class="col-sm-10">
						      	<textarea class="form-control" cols="40" id="id_text" name="text" rows="3" required=""></textarea>
						      	{{ form.text.errors }}
						    </div>
						</div>
  						<div class="form-group">
  							<label class="col-sm-2 control-label" >提交</label>
    						<div class="col-sm-10">
      							<button type="submit"><span>(=ﾟωﾟ)ﾉ</span></button>
    						</div>
  						</div>
  					</div>
  				</form>
			</div>
			<hr />
			<div class="panel panel-default">
  				<!-- Default panel contents -->
			  <div class="panel-heading">小想法们</div>
			  <div class="panel-body">
			    <p>感谢每一个评论过的人Thanks♪(･ω･)ﾉ</p>
			  </div>

			  <!-- List group -->
			  <ul class="list-group">
			  	{% for comment in comment_list %}
			    <li class="list-group-item">
			    	<div class="panel panel-default">
			    		<div class="panel-body">
			    			<p>{{ comment.text }}</p>
			    		</div>
				    	<div class="panel-footer">
				    		<p>
				    			<span class="fa fa-user-secret fa-fw"></span>{{ comment.name }}&nbsp;&nbsp;<span class="fa fa-clock-o fa-fw"></span>{{ comment.created_time }}
				    		</p>
				    	</div>
			  		</div>
			    </li>
			    {% empty %}
			    <li>
				暂无评论(*/ω＼*)
				</li>
				{% endfor %}
			  </ul>
			</div>
		</div>
		<div class="col-md-3 col-sm-4 col-xs-2">
		</div>
	</div>
</div>
{% endblock basemain %}

VenvProjectBlog/templates/blog/index.html
{% extends 'base.html' %}
{% block main %}

<div class="container-fluid">
	<div class="row">
		<div class="col-md-4 col-sm-2 col-xs-0">
		</div>
		<div class="col-md-7 col-sm-9 col-xs-12">
			{% if error_msg %}
			<div class="alert alert-{{text_css}} alert-dismissible" role="alert">
			  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			  <strong>{{error_msg}}</strong>
			</div>
			{% endif %}
			{% for post in post_list %}
				<div class="panel">
	  				<div class="panel-body">
	  					<p class="text-left">
	  						{{ post.author }}<em><i class="fa fa-clock-o fa-fw"></i>{{ post.created_time }}</em>
	  					</p>
	  					<h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
	  					<p style="font-size:18px">
	  						{{ post.excerpt }}
	  					</p>
	  				</div>
	  				<div class="panel-footer">
	  					<p>
	  					<a href="#" class="label label-primary">{{ post.category.name }}</a>&nbsp;&nbsp;&nbsp;&nbsp;<span class="fa fa-comments fa-fw"></span>(1)&nbsp;&nbsp;&nbsp;<span class="fa fa-eye fa-fw"></span>(1)&nbsp;&nbsp;&nbsp;<span class="fa fa-thumbs-o-up fa-fw"></span>(1)
	  					</p>
	  				</div>
				</div>
				<hr/>
			{% empty %}
			<div class="no-post">暂时没有文章</div>
			{% endfor %}
		</div>
		<div class="col-md-1 col-sm-1 col-xs-0">
		</div>
	</div>
</div>
{% endblock main %}

VenvProjectBlog/templates/blog/list.html
{% extends 'base.html' %}
{% block main %}

<div class="container-fluid">
	<div class="row">
		<div class="col-md-4 col-sm-2 col-xs-0">
		</div>
		<div class="col-md-7 col-sm-9 col-xs-12">
			{% if error_msg %}
			<div class="alert alert-{{text_css}} alert-dismissible" role="alert">
			  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			  <strong>{{error_msg}}</strong>
			</div>
			{% endif %}
			{% for post in post_list %}
				<div class="panel">
	  				<div class="panel-body">
	  					<p class="text-left">
	  						{{ post.author }}<em><i class="fa fa-clock-o fa-fw"></i>{{ post.created_time }}</em>
	  					</p>
	  					<h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
	  					<p style="font-size:18px">
	  						{{ post.excerpt }}
	  					</p>
	  				</div>
	  				<div class="panel-footer">
	  					<p>
	  					<a href="#" class="label label-primary">{{ post.category.name }}</a>&nbsp;&nbsp;&nbsp;&nbsp;<span class="fa fa-comments fa-fw"></span>(-)&nbsp;&nbsp;&nbsp;<span class="fa fa-eye fa-fw"></span>({{post.showNum}})&nbsp;&nbsp;&nbsp;<span class="fa fa-thumbs-o-up fa-fw"></span>(-)
	  					</p>
	  				</div>
				</div>
				<hr/>
			{% empty %}
			<div class="no-post">暂时没有文章</div>
			{% endfor %}
			<nav aria-label="...">
			  <ul class="pager">
			  	{% if post_list.has_previous %}
			    <li class="previous"><a href="?page={{ post_list.previous_page_number }}"><span aria-hidden="true">&larr;</span>上一页</a></li>
			    {% else %}
			    <li class="previous disabled"><a href="#"><span aria-hidden="true">&larr;</span>上一页</a></li>
			    {% endif %}
			    <li>第-{{ post_list.number }}-页/共{{ post_list.paginator.num_pages }}页</li>
			    {% if post_list.has_next %}
			    <li class="next"><a href="?page={{ post_list.next_page_number }}">下一页<span aria-hidden="true">&rarr;</span></a></li>
			    {% else %}
			    <li class="next disabled"><a href="#">下一页<span aria-hidden="true">&rarr;</span></a></li>
			    {% endif %}
			  </ul>
			</nav>
		</div>
		<div class="col-md-1 col-sm-1 col-xs-0">
		</div>
	</div>
</div>
{% endblock main %}

VenvProjectBlog/templates/blog/main.html
{% extends 'basemain.html' %}
{% block basemain %}
<div class="row">
	<div class="col-md-2 col-sm-1 col-xs-0"></div>
	<div class="col-md-8 col-sm-10 col-xs-12">
		<div class="jumbotron">
		  <h1>{{main.title}}</h1>
		  	{{ main.body|safe }}
		</div>
		<div class="well well-sm"><p style="text-align: right">编辑时间:{{main.create_time}}&nbsp;&nbsp;&nbsp;&nbsp;作者:{{main.author}}</p></div>
	</div>
	<div class="col-md-2 col-sm-1 col-xs-0"></div>
</div>
{% endblock basemain %}